# Generated by Django 5.2.3 on 2025-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='hashtag',
            field=models.CharField(default='', max_length=255),
        ),
    ]
